### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by THJLearn** [sfyr111/egg-commerce#4]
2019-12-30 17:53:49,686 INFO 5119 [master] node version v12.13.1
2019-12-30 17:53:49,688 INFO 5119 [master] egg version 2.26.0
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:245:13
assert.js:374
    throw err;
    ^

AssertionError [ERR_ASSERTION]: config.alinode.appid required
    at module.exports (/Users/zhaoyoulu/Documents/nodelsLearn/product/egg-commerce/node_modules/egg-alinode/agent.js:15:3)
    at Hook.configDidLoad (/Users/zhaoyoulu/Documents/nodelsLearn/product/egg-commerce/node_modules/egg-core/lib/lifecycle.js:91:9)
    at Lifecycle.triggerConfigDidLoad (/Users/zhaoyoulu/Documents/nodelsLearn/product/egg-commerce/node_modules/egg-core/lib/lifecycle.js:145:14)
    at Lifecycle.triggerConfigWillLoad (/Users/zhaoyoulu/Documents/nodelsLearn/product/egg-commerce/node_modules/egg-core/lib/lifecycle.js:139:10)
    at AgentWorkerLoader.loadCustomAgent (/Users/zhaoyoulu/Documents/nodelsLearn/product/egg-commerce/node_modules/egg-core/lib/loader/mixin/custom.js:45:20)
    at AgentWorkerLoader.load (/Users/zhaoyoulu/Documents/nodelsLearn/product/egg-commerce/node_modules/egg/lib/loader/agent_worker_loader.js:23:10)
    at new Agent (/Users/zhaoyoulu/Documents/nodelsLearn/product/egg-commerce/node_modules/egg/lib/agent.js:24:17)
    at Object.<anonymous> (/Users/zhaoyoulu/Documents/nodelsLearn/product/egg-commerce/node_modules/egg-cluster/lib/agent_worker.js:28:15)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: '',
  expected: true,
  operator: '=='
}
2019-12-30 17:53:51,144 ERROR 5119 nodejs.AgentWorkerDiedError: [master] agent_worker#1:5120 died (code: 1, signal: null)
    at Master.onAgentExit (/Users/zhaoyoulu/Documents/nodelsLearn/product/egg-commerce/node_modules/egg-cluster/lib/master.js:425:17)
    at Master.emit (events.js:210:5)
    at Messenger.sendToMaster (/Users/zhaoyoulu/Documents/nodelsLearn/product/egg-commerce/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/Users/zhaoyoulu/Documents/nodelsLearn/product/egg-commerce/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
    at ChildProcess.<anonymous> (/Users/zhaoyoulu/Documents/nodelsLearn/product/egg-commerce/node_modules/egg-cluster/lib/master.js:289:22)
    at Object.onceWrapper (events.js:300:26)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
name: "AgentWorkerDiedError"
pid: 5119
hostname: zhaoyouludeMacBook-Air.local

2019-12-30 17:53:51,144 ERROR 5119 [master] agent_worker#1:5120 start fail, exiting with code:1
2019-12-30 17:53:51,144 ERROR 5119 [master] exit with code:1
Error: /Users/zhaoyoulu/Documents/nodelsLearn/product/egg-commerce/node_modules/egg-bin/lib/start-cluster {"port":7001,"workers":1,"baseDir":"/Users/zhaoyoulu/Documents/nodelsLearn/product/egg-commerce","framework":"/Users/zhaoyoulu/Documents/nodelsLearn/product/egg-commerce/node_modules/egg"} exit with code 1
    at ChildProcess.<anonymous> (/Users/zhaoyoulu/Documents/nodelsLearn/product/egg-commerce/node_modules/common-bin/lib/helper.js:56:21)
    at Object.onceWrapper (events.js:300:26)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12) {
  code: 1
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egg-commerce@1.0.0 dev: `egg-bin dev --port 7001`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the egg-commerce@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhaoyoulu/.npm/_logs/2019-12-30T09_53_51_164Z-debug.log
zhaoyoulu@zhaoyouludeMacBook-Air egg-commerce %

**Comment by zjh1002492540** [comment]
配置数据库链接；注释掉alinode那个插件就可以了
